### ISSUE TITLE
Track URL path

### ISSUE THREAD

**Issue by ericandrewlewis** [ronlut/graylog-content-pack-nginx-docker#1]
Would it be possible to track the URL path as a separate field?

**Comment by ronlut** [comment]
Hi.
I'm currently abroad and not in front of a computer.

Try adding `' "url_path": "$uri", '` or `' "url_path": "$request_uri", '` to the `graylog2_json` configuration.

You can lookup for additional variables [here](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_document_uri)

Example of `$request_uri`: [link](https://www.webhosting24.com/understanding-nginx-request_uri/)

Hope that helps :)

**Comment by ronlut** [comment]
Closing, let me know if something is unclear

**Comment by ericandrewlewis** [comment]
Thanks for the notes!

Do you mind if I add a bit of explainer text to the README about logging other NGINX embedded variables? Something like:

> You can log other useful information for each request by adding [the desired NGINX variable](http://nginx.org/en/docs/http/ngx_http_core_module.html#variables) into the JSON.

**Comment by ronlut** [comment]
Sure, go ahead!
And thanks for the help 😀

**Comment by ericandrewlewis** [comment]
Cool - created https://github.com/ronlut/graylog-content-pack-nginx-docker/pull/2
